### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by amirouche** [franckinux/my-own-little-business#3]
J'ai installé l'application et j'ai essayé de faire une commande, voilà la trace que j'obtiens:

```python
2018-04-05 23:54:44 +0200] [22386] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/error.py", line 9, in middleware_handler
    response = await handler(request)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 132, in factory
    response = await handler(request)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp_session_flash/__init__.py", line 31, in process
    response = yield from handler(request)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 114, in middleware
    return (yield from handler(request))
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/auth/__init__.py", line 15, in wrapped
    return await f(request)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 99, in wrapped
    app_key=app_key, encoding=encoding)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 71, in render_template
    text = render_string(template_name, request, context, app_key=app_key)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp_jinja2/__init__.py", line 62, in render_string
    text = template.render(context)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/list-order.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/base.html", line 28, in block "content"
    {% block page_content %}{% endblock %}
  File "/home/amirouche/src/python/ii/my-own-little-business/molb/templates/list-order.html", line 31, in block "page_content"
    <td><a href="{{ url("edit_order", id=order.id) }}">{{ order.order_date.strftime("%Y-%m-%d %H:%M") }}</a></td>
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp_jinja2/helpers.py", line 23, in url_for
    url = app.router[__route_name].url_for(**parts)
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 448, in url_for
    for k, v in parts.items()})
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/aiohttp/web_urldispatcher.py", line 448, in <dictcomp>
    for k, v in parts.items()})
  File "/home/amirouche/.virtualenvs/molb/lib/python3.6/site-packages/yarl/__init__.py", line 205, in build
    path = cls._PATH_QUOTER(path)
  File "yarl/_quoting.pyx", line 226, in yarl._quoting._Quoter.__call__
TypeError: Argument should be str
[2018-04-05 23:54:57 +0200] [22382] [INFO] Handling signal: winch
```

**Comment by franckinux** [comment]
Merci du rapport de bug !!
En fait, il faut mettre des string dans les méthodes url(). Avant le passage à aiohttp 3.0, ça marchait !
Je corrige ça.
